#!/bin/bash
set -e

echo "=== GitHub + Terraform + AWS Setup ==="
echo ""
echo "已创建的AWS资源："
echo "✅ OIDC Provider: arn:aws:iam::058264116877:oidc-provider/token.actions.githubusercontent.com"
echo "✅ IAM Role: arn:aws:iam::058264116877:role/GitHubActionsTerraformRole"
echo "✅ S3 Bucket: terraform-state-058264116877"
echo "✅ DynamoDB Table: terraform-state-lock"
echo ""
echo "下一步操作："
echo ""
echo "1. 在GitHub上创建新仓库（或使用现有仓库）"
echo ""
echo "2. 初始化并推送代码："
echo "   cd /tmp/github-terraform-setup"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial Terraform setup with GitHub Actions'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/YOUR_ORG/YOUR_REPO.git"
echo "   git push -u origin main"
echo ""
echo "3. 在GitHub仓库中配置Environment保护（实现Approval）："
echo "   - 进入: Settings → Environments → New environment"
echo "   - 名称: production"
echo "   - 勾选: Required reviewers"
echo "   - 添加审批者（你的GitHub用户名或团队）"
echo "   - 保存"
echo ""
echo "4. （可选）限制IAM角色只能被特定仓库使用："
echo "   aws iam update-assume-role-policy \\"
echo "     --role-name GitHubActionsTerraformRole \\"
echo "     --policy-document file:///tmp/github-terraform-setup/trust-policy-specific-repo.json"
echo ""
echo "5. 测试工作流："
echo "   - 创建新分支并修改terraform/resources.tf"
echo "   - 创建Pull Request"
echo "   - 查看自动生成的Terraform Plan"
echo "   - 合并PR后需要审批才能Apply"
echo ""
echo "所有文件已准备在: /tmp/github-terraform-setup/"
